### ISSUE TITLE
Klapwijk et al. Sample size estimation for task-related functional MRI studies using Bayesian updating

### ISSUE THREAD

**Issue by eduardklap** [codecheckers/register#100]
**Repository**: https://github.com/eduardklap/sample-size-codecheck

**Certificate**: `2024-005`

**Comment by nuest** [comment]
Hi @eduardklap ! Thanks for opening the PR - can you give me some context on the background, please? Are you working in the context of CHECK-NL or with AUMC?

**Comment by eduardklap** [comment]
Hi @nuest, thanks for your message! Although I am involved in the organisation of the CHECK-NL workshop on 28 November in Rotterdam, this PR is just because I want to get my own paper checked 😄 
I tried to follow the [CODECHECK instructions for authors](https://codecheck.org.uk/guide/community-workflow#submission) and opened this PR. Would it be possible to codecheck this manuscript?

**Comment by nuest** [comment]
@foost Just because of spatial proximity - what do you think about approaching one of the recently added people from CHECK-NL events? See the last few lines at https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv

**Comment by eduardklap** [comment]
Hi both, just FYI in principle everyone with RStudio/Quarto installed should be able to rerun the analyses (at least, that is what I aimed for 😄), maybe that helps in finding someone to do the checking

**Comment by nuest** [comment]
@LukasRoeseler would you be available to conduct a community CODECHECK here for a preprint?

Since this is your first one, I'd follow along a bit closer, we can also have a short call at the start and towards the end of your reproduction. Apart from that, everything you need to know should be in https://codecheck.org.uk/guide/community-workflow (and we're always looking for feedback).

@eduardklap Did you submit the paper already? Would you be able or interested to reference the check in the paper?

**Comment by eduardklap** [comment]
I did submit the paper and I would love to reference the check in the paper. Revision date is due beginning of October, so it would be great if it can be checked in the meantime. Thanks in advance!

**Comment by LukasRoeseler** [comment]
I am unavailable this week and next week, so I may not be able to make it until beginning of October. If this is not a problem, I will gladly accept the codecheck!

Also for clarity, I have not attended the CHECK-NL events.

**Comment by eduardklap** [comment]
Thanks Lukas! I think I will manage to squeeze it in the paper (will already add a sentence about the CODECHECK, can later add the doi if everything goes well)
Looking forward to your findings!

**Comment by nuest** [comment]
Excellent!

Thanks @LukasRoeseler - let me know when you have taken a look at the documentation, and then we can schedule a short call so I can help you get started.

**Comment by eduardklap** [comment]
Hi folks, just wanted to check if you think it is feasible to do the codecheck in the near future?
Would be great since I am finishing up the revision. Thanks in advance!

**Comment by LukasRoeseler** [comment]
Hi, Daniel and I met today and I am ready to start now. I will try to get this done this week. I am very sorry for the long delay!

**Comment by eduardklap** [comment]
Great to hear that, thanks so much!

1. I think the best way to go is to first fork the repository, then you are able to make the changes in your own fork. Checking with @nuest if this should indeed be the workflow?
2. Thanks for checking this, there was a typo in the yaml file. I just corrected it and pushed the updated file to the repo: now it should be fine

**Comment by nuest** [comment]
Yes, that's possible.

@LukasRoeseler Please fork into the `codecheckers` organisation, you should have the rights to do that.

@eduardklap It would be great though if you accept the subsequent PR to update the CODECHECK configuration file, only then can we use this repository as the "checked repository", because that is where the normative metadata record should be.

@LukasRoeseler This is probably something we can improve in the workflow. In case the author does not react, we can use our fork. In this case, I think we can update the author's repo though. The fork is also useful because an author may just completely overhaul their project or even remove it, while we keep our clone "as is" at the time of the check. IIRC the workflow should tell you to fork and eventually also "archive" the fork.

**Comment by LukasRoeseler** [comment]
I finished the codecheck. The zenodo preprint is published and the final report is available in the codecheck folder: https://github.com/codecheckers/sample-size-codecheck/blob/main/codecheck/codecheck.pdf

Rösel, L. (2024). CODECHECK certificate 2024-005. Zenodo. https://doi.org/10.5281/zenodo.13945051

**Comment by nuest** [comment]
@eduardklap Congratulations on a successful check!

It would be great if you can incorporate the check in your submission. We're also always interest in conversations with journals, so if your handling editor picks up on the check feel free to point them to us or maybe you can make a joint conversation happen.

Thank you for your contribution to advancing research towards more open and reproducible research!

**Comment by eduardklap** [comment]
Great news! Thank you so much for checking @LukasRoeseler and sorry for consuming all those computing hours :)
Thank you @nuest for organizing the whole check so nicely. Will definitely cite the check and the CODECHECK project in the resubmission of the paper. Will also put the editors in contact in case they are interested.

**Comment by LukasRoeseler** [comment]
You're welcome @eduardklap, thank you for making the check so easy for me! And apologies for taking so long!

**Comment by nuest** [comment]
@eduardklap If I may as for a favour: The check by Lukas is the first one done by an "external" person in a long time, and he unfortunately encoutered outdated documentation and shared very valuable feedback with us.

Since your repository included a `codecheck.yml` file I assume you took a look at our documentation (e.g., https://codecheck.org.uk/guide/community-workflow) from the author's perspective. Would you be so kind and share your experience with me, either via email or we can also have a short call, if that is easier for you. Thanks!

**Comment by eduardklap** [comment]
Yes, definitely. I will send you an email today!
