### ISSUE TITLE
Multiple certs have the same identifier

### ISSUE THREAD

**Issue by angelina-momin** [codecheckers/register#128]
There are multiple codecheck certificates with the same identifier.
See here in the register: [link](https://github.com/codecheckers/register/blob/master/register.csv#L70-L81)

I was under the impression that each certificate should have a unique identifier. 
Because multiple codecheck certificates have the same identifier the certificate page only displays information for one of the cert.

For instance there are two certs with the identifier "2024-006" but only one of them is displayed in the link: https://codecheck.org.uk/register/certs/2024-006/

Maybe we should add a check in the register and codecheck repos to identify when this happens and throw an error.

**Comment by nuest** [comment]
You are absolutely right - and this should indeed be checked during the register rendering.

I fixed the certificate identifiers, nobody external uses these yet.

I also came across a bunch of validation errors for the AGILEGIS certificats from 2023 - because the yml files were incomplete :facepalm: > see https://github.com/reproducible-agile/reviews-2023/commit/64a56012440c18d0d50a9700b86780917a553e2f

So, in sum: https://github.com/codecheckers/codecheck/issues/9 should be considered by me soon.
