### ISSUE TITLE
Fichera et al

### ISSUE THREAD

**Issue by sje30** [codecheckers/register#133]
**Repository**: https://github.com/codecheckers/Inter_Noise2024_Codes_Acoustics_Diffusion_Equation

**Certificate**:  `2024-017`

**Comment by sje30** [comment]
This was from Delft, May 2024.

**Comment by nuest** [comment]
Status: sent to author, certificate not yet published. Correct?

**Comment by nuest** [comment]
The paper DOI seems to be https://doi.org/10.3397/IN_2024_3491

But that does not give access to the paper. You have the actual link in the certificate...

Use the publisher DOI or not?

-------

I'm pondering to handle more cases in the `codecheck.yml` with proper fields, but struggled so far to find the time to implement that.

**Comment by sje30** [comment]
hi Daniel,
yes, that is the paper, but paywalled.  Would prefer to link to a preprint version rather than publisher DOI.  I can make a note in the cert.  Cert is done (very late, down to me) but just checking with co-authors (who were at the workshop).

**Comment by nuest** [comment]
A note to the published paper in the certificate would be good!

Even if this does not feel perfect from a open research information perspective... but that's why we're doing all these community checks, to get these experiences (end of reminder to myself), see https://github.com/codecheckers/discussion/issues/3#issuecomment-2462560178

**Comment by sje30** [comment]
Finally published today...
