### ISSUE TITLE
Add a codechecker view to the register

### ISSUE THREAD

**Issue by nuest** [codecheckers/register#30]
The register could compile a codechecker profile page for each person contributing as a CODECHECKER.

1. Add a new page `https://codecheck.org.uk/register/codechecker/<GH handle>` (or better `ORCID` ?); content:
    * how many codechecks for which types were done (graphic)
    * list of all codechecks as links
    * list of journals/venues for which codechecks were completed
    * link to GitHub profile
    * link to ORCID profile (in correct formatting, see https://info.orcid.org/brand-guidelines/)
    * pull a profile image from GitHub
4. Design options
    * Use a table just as for the register
    * "cards" would be nice but also more work in markdown.
 5. Add JSON output format, i.e., https://codecheck.org.uk/register/codechecker/0000-0000-0000-0000.json) with machine-readable metadata and a list of certificate IDs per ORCID
6. To `stats.json`, add the number of codecheckers.

**Comment by nuest** [comment]
Layout:

- https://dev.to/bendman/a-responsive-card-list-i00
- https://codepen.io/ryamakuchi/pen/LYExRpa
- https://www.w3schools.com/w3css/w3css_cards.asp
- thumbnail list from https://designshack.net/articles/css/5-simple-and-practical-css-list-styles-you-can-copy-and-paste/
- https://codemyui.com/card-style-list-pure-css/
- https://onaircode.com/html-css-card-layout-examples/

**Comment by nuest** [comment]
The `gluedown` package might help, if we use Rmd and not just plain Jekyll: https://kiernann.com/gluedown/

**Comment by sje30** [comment]
happy to use Rmd for this, and hence gluedown.  re: layout specifics, I'm not sure which is best (what is easiest for now, and if we can easily swap out one for another, does it matter what we choose?)

**Comment by nuest** [comment]
Right now everything is plain Jekyll, so not using R Markdown is probably easier. Will see, this is not high on the list yet with just the two of us as checkers ;-)

**Comment by angelina-momin** [comment]
@nuest and @sje30 Couple of questions I need to ask about this feature:

1. Do you want the rendered register tables to have a "codechecker" column or should I leave the rendered registered table as it is? 

If you prefer the former how would you like the string to be formatted? Some of the formats I could think of
`{codechecker_name} (ORCID: {orcid_id})` 
`{codechecker_name} ({orcid_id})` 
`{orcid_id}` 
`{codechecker_name}`

For the formats with the ORCID IDs I can add hyperlinks to the corresponding ORCID pages if you'd like.

2. Is there a preference on whether to use ORCID ID or GitHub handle for the link? 

I personally lean towards the ORCID ID atm because the codecheck.yaml files only contain the ORCID IDs of the codecheckers but not the GitHub handle. While it may be possible to look up GitHub handles for a specified name using GitHub API it may prove to be tricky for cases where using the full name does not return the correct GitHub handle or there are multiple users with the same full name?

3. What would you like as the title of the rendered files? Some of the formats I could think of

`Register for codechecks by {codechecker_name} (ORCID: {orcid_id})` 
`Register for codechecks by {codechecker_name} ({orcid_id})` 
`Register for codechecks by ORCID ID: {orcid_id}`
`Register for codechecks by {codechecker_name}` 

For the last format we could add the ORCID ID as a subtitle.

**Comment by nuest** [comment]
https://codecheck.org.uk/register/codecheckers/0000-0002-0024-5046/

![image](https://github.com/user-attachments/assets/84760503-31ec-414b-8449-3992264f41c4)
