### ISSUE TITLE
[Vieira et al] Driftage paper

### ISSUE THREAD

**Issue by sje30** [codecheckers/register#31]
**Repository**: https://github.com/codecheckers/driftage

**Certificate**: ~~`2020-025`~~ `2020-024`

**Comment by sje30** [comment]
drafted; just awaiting a check of how to cite the paper.

**Comment by nuest** [comment]
@sje30 Cool to hear - is this a community one, or did you do this as a reviewer for a journal? Note I added the certificate ID in the first comment.

**Comment by sje30** [comment]
journal requested.

**Comment by nuest** [comment]
@sje30 We've been using different approaches in our latest checks with journals. I'm waiting for the DOI from the journal to publish, while you published with a "under review" reference. Just wanted to note that, probably good to have that flexibility and possibly serve journal specific processes.

I suggest to keep this issue open, because the final reference should be updated in the `codecheck.yml` when it is out. Also, it would be good to reference the paper from the Zenodo metadata.

- [ ] add reference to `codecheck.yml`
- [ ] update Zenodo record: updated PDF with paper DOI, add DOI to Zenodo related identifiers

**Comment by nuest** [comment]
Paper still not published, it seems... :hourglass_flowing_sand:

**Comment by sje30** [comment]
I believe it was accepted for publication a week or so ago...

**Comment by nuest** [comment]
Paper still not published..

**Comment by nuest** [comment]
Paper is finally published:

> Diogo Munaro Vieira, Chrystinne Fernandes, Carlos Lucena, Sérgio Lifschitz, Driftage: a multi-agent system framework for concept drift detection, GigaScience, Volume 10, Issue 6, June 2021, giab030, https://doi.org/10.1093/gigascience/giab030

@sje30 I updated the codecheck.yml (https://github.com/codecheckers/driftage/commit/da12223356fbbb6ad0eb11fdfb07602ba9de2ca2) - can you please update the PDF on Zenodo?

**Comment by nuest** [comment]
Certificate PDF was already updated a while ago - see https://zenodo.org/record/4964880

**Comment by nuest** [comment]
Updated report DOI in codecheck.yml in https://github.com/codecheckers/driftage/commit/6ab5919ca5bb50efacf179e763ce53d8a1ac6e04
