### ISSUE TITLE
[Vargas, Gagnon] Geographically Weighted Regressions for prioritizing educational planning, policies, and interventions

### ISSUE THREAD

**Issue by sje30** [codecheckers/register#40]
**Repository**: https://github.com/codecheckers/GWR-in-educational-planning

**Certificate**: `2022-001`

**Comment by sje30** [comment]
Certificate now uploaded via df3dcf03564b56823f9ea6b1f16621c7b4db626f

**Comment by nuest** [comment]
Note for the record, no action needed here — leaving this issue closed.

As part of the register-wide Zenodo metadata curation (#205) the certificate for 2022-001 needed its licence changed to CC-BY 4.0, per the CODECHECK [community curation policy](https://zenodo.org/communities/codecheck/curation-policy). Editing the licence on the existing record was refused by Zenodo with `Files are not enabled`, an API limitation on some older deposits, so the change was made by publishing a **new version** of the record instead:

* previous version: https://doi.org/10.5281/zenodo.6040066
* new version: https://doi.org/10.5281/zenodo.6043785

The concept DOI is unchanged, so the existing citation keeps resolving to the latest version. The certificate PDF is identical; only the metadata differs.

The `report` DOI in the repository's `codecheck.yml` still points at the previous version and needs updating so the register links to the new one. The repository [codecheckers/GWR-in-educational-planning](https://github.com/codecheckers/GWR-in-educational-planning) is archived, so that change is pending until it is temporarily unarchived.

**Comment by nuest** [comment]
Follow-up: [codecheckers/GWR-in-educational-planning](https://github.com/codecheckers/GWR-in-educational-planning) has been temporarily unarchived, so the pending `codecheck.yml` change is now open as codecheckers/GWR-in-educational-planning#2.
