### ISSUE TITLE
Ruining Dong, Daniel Cameron, Justin Bedo, Anthony T Papenfuss

### ISSUE THREAD

**Issue by rgaiacs** [codecheckers/register#44]
**Repository**: https://gitlab.com/raniere-phd/codecheck-svaretro-and-svanumt requires to me migrated 

**Certificate**: `2022-018`

**Comment by nuest** [comment]
I confirm the ID is the next one up. Please don't forget to add it to your report.

Feedback on the report draft was given via email.

**Comment by rgaiacs** [comment]
@nuest the CODECHECK report was deposited at https://doi.org/10.5281/zenodo.7030412

**Comment by nuest** [comment]
Thanks! We'll go ahead with the deposition once the publisher has answered the questions regarding the upcoming procedures. Would be great if you could push that along a little bit ;-)

**Comment by rgaiacs** [comment]
@nuest v2 of the CODECHECK report was deposited at https://doi.org/10.5281/zenodo.7084333.

Can you remember what is missing to close this issue?

**Comment by stm** [comment]
@rgaiacs I'm not sure what to do – the [`codecheck.yml`](https://gitlab.com/cdchck/community-codechecks/2022-svaRetro-svaNUMT/-/blob/main/codecheck.yml) in the GitLab repo has already been updated with commit [cdchck/community-codechecks/2022-svaRetro-svaNUMT@e829822b](https://gitlab.com/cdchck/community-codechecks/2022-svaRetro-svaNUMT/-/commit/e829822b2cf7499384c238d0c413aee1fd6f61ba) with the new DOI.

**Comment by nuest** [comment]
Two problems:

1. Some metadata was missing from `codecheck.yml` - fixed that in https://gitlab.com/cdchck/community-codechecks/2022-svaRetro-svaNUMT/-/commit/ecd8913a97cac73578df609543a7b09bd2c35171
2. There was no code yet to retrieve `gitlab` remotes, which was fixed in https://github.com/codecheckers/codecheck/commit/f932150450975979276bb46cf7a8fcd1ba293ce3

**Comment by sje30** [comment]
hi, two issues with the cert:

1. in table 1, the bottom row -- the word Repository seems to run into
the URL so that the URL (gitlab) doesn't work.

2. the two issues (bottom p2/top p3) -- can the author fold them back
into their repo to fix this?

S

**Comment by nuest** [comment]
@rgaiacs — reopening this issue with a request, sorry for the noise on an old thread.

We now check every certificate in the register against the [CODECHECK community curation policy](https://zenodo.org/communities/codecheck/curation-policy) as part of the register rendering, and are working through the records that do not yet follow it (see #205). Most were corrected centrally, but your Zenodo record cannot be edited because the deposit belongs to your account.

So this one needs you. The changes for [zenodo.org/records/7084333](https://zenodo.org/records/7084333):

| Field | Current | Should be |
| --- | --- | --- |
| Publisher | `Zenodo` | `CODECHECK Community on Zenodo` |
| Resource type | `other` | `Publication / Report` |
| Related work | — | Relation `Reviews`, DOI `10.46471/gigabyte.70`, resource type Publication |
| Related work | — | Relation `Is supplemented by`, URL https://gitlab.com/cdchck/community-codechecks/2022-svaRetro-svaNUMT, resource type Software |
| Alternate identifier | — | `http://cdchck.science/register/certs/2022-018`, scheme `URL` |
| Alternate identifier | — | `cdchck.science/register/certs/2022-018`, scheme `Other` |
| Community | not in the CODECHECK community | submit the record to [the CODECHECK community](https://zenodo.org/communities/codecheck/) |

All of these are editable via *Edit* on the record page; none of them create a new version or change the DOI.

If you would rather not do it by hand, you can grant edit access instead and we will apply it for you: on the record page click **Share**, then under the **People** tab click **Add people**, search the **User** field for `nuest` or `daniel.nuest@tu-dresden.de`, set **Access** to **Can edit** and click **Add**. (If the search doesn't find that account, just say so here and we'll sort it out.) Either way, please close this issue again when done — or say so here and we will.

Thanks for the original codecheck, and sorry to come back to it four years later.
