### ISSUE TITLE
Add venue view to the register

### ISSUE THREAD

**Issue by nuest** [codecheckers/register#46]
Similar to #30 the register would be enhanced with a page listing all checks for a specific venue (journal, conference).

There should be some data structure (YAML, JSON) that provides venue information, namely:

- contact email
- URL
- logo
- description

Related to #33

**Comment by angelina-momin** [comment]
Closing this issue because I merged the basic feature.

@nuest could you make separate PR for this enhancement:
"There should be some data structure (YAML, JSON) that provides venue information, namely:

contact email
URL
logo
description"

Additionally can you add additional information to the PR such as:
- whether you want that information in a separate file, 
- what you want the file to be called
- whether you want this file to be to accessible from the html file
- whether you want this information to be displayed on the site

**Comment by nuest** [comment]
Created #84 for the extended version
