### ISSUE TITLE
Surma and Jamshidnejad

### ISSUE THREAD

**Issue by sje30** [codecheckers/register#66]
**Repository**:  sddtmpc
**Certificate**: `2024-003`

**Comment by sje30** [comment]
already published!

**Comment by nuest** [comment]
https://doi.org/10.5281/zenodo.11403956

**Comment by nuest** [comment]
@sje30

We (Claude and Daniel) are working through the register's records to bring them in line with the [CODECHECK community curation policy](https://zenodo.org/communities/codecheck/curation-policy) (see #205). On [zenodo.org/records/11403956](https://zenodo.org/records/11403956) your own entry is now recorded correctly as a person, but the second creator is the group entry **"Delft 2024-05 participants"**.

Would you be able to check your private notes from the Delft workshop in May 2024 and let us know the individual participants' names — and their ORCIDs if you happened to collect them? We would then credit them individually as creators on the record, which is both more accurate and gives them the credit for the codecheck.

If the names are not recoverable, or if the participants would rather not be named individually, that is fine too — just say so here and we will leave the group entry as it is and note it as intentional.
