### ISSUE TITLE
[Kucharski et al 2020]  Model of isolation, contact tracing, and physical distancing

### ISSUE THREAD

**Issue by sje30** [codecheckers/register#9]
**Repository**: https://github.com/codecheckers/2020-cov-tracing

**Certificate**: `2020-009`

**Comment by sje30** [comment]
@sje30 assigned.

**Comment by nuest** [comment]
@sje30 You're working on this, right? Or do you need help?

**Comment by sje30** [comment]
all done!  https://zenodo.org/record/3767060

can the register be updated online?  (Is the register visible from our home page?)

**Comment by nuest** [comment]
@sje30 The register currently must be updated manually. I'm happy to set up a CI process that does this, i.e., that you would only have to edit `register.csv` and then the CI makes a commit a little bit later and updates the `regsiter.md` and the `docs/` folder with the website.

Should we do that? @sje30

**Comment by sje30** [comment]
great re: CI.

was thinking we should have the certificates visible from our front page of codecheck.org.uk

**Comment by nuest** [comment]
I'll make adding the certificates to the front page the next thing I do for CODECHECK.

**Comment by nuest** [comment]
https://github.com/codecheckers/register/issues/17

**Comment by nuest** [comment]
![image](https://user-images.githubusercontent.com/1325054/83525420-3e6cb880-a4e5-11ea-9117-279a3d945149.png)

Done.

**Comment by sje30** [comment]
awesome!

**Comment by nuest** [comment]
Note for the record, no action needed here — leaving this issue closed.

As part of the register-wide Zenodo metadata curation (#205) the certificate for 2020-009 needed its licence changed to CC-BY 4.0, per the CODECHECK [community curation policy](https://zenodo.org/communities/codecheck/curation-policy). Editing the licence on the existing record was refused by Zenodo with `Files are not enabled`, an API limitation on some older deposits, so the change was made by publishing a **new version** of the record instead:

* previous version: https://doi.org/10.5281/zenodo.3767060
* new version: https://doi.org/10.5281/zenodo.22109593

The concept DOI is unchanged, so the existing citation keeps resolving to the latest version. The certificate PDF is identical; only the metadata differs.

The `report` DOI in the repository's `codecheck.yml` still points at the previous version and needs updating so the register links to the new one. The repository [codecheckers/2020-cov-tracing](https://github.com/codecheckers/2020-cov-tracing) is archived, so that change is pending until it is temporarily unarchived.

**Comment by nuest** [comment]
Follow-up: [codecheckers/2020-cov-tracing](https://github.com/codecheckers/2020-cov-tracing) has been temporarily unarchived, so the pending `codecheck.yml` change is now open as codecheckers/2020-cov-tracing#2.
